version: '3'
services:
  merkl-lite:
    image: merkl-lite
    build:
      context: .
      args:
        SDK_READ_ACCESS_TOKEN: $GITHUB_REGISTRY_TOKEN
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - .env
    environment:
      - PORT=5173
    volumes:
      - ./src:/app/src
      - ./app:/app/app
